version: '3.3'
services:
  epochtalk-api-tests:
    image: quay.io/epochtalk/epochtalk-api-tests
    ports:
      - "1025:1025"
    depends_on:
      - epochtalk
    links:
      - epochtalk
    environment:
      HOST: http://epochtalk:8080
    command: sh -c "./wait-for-it.sh epochtalk:8080 -t 120 && sleep 5 && npm run test"
  protractor:
    build: .
    depends_on:
      - epochtalk
      - chrome
    links:
      - epochtalk
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: password
      SELENIUM_HOST: http://chrome
      SELENIUM_PORT: 4444
      SELENIUM_EPOCHTALK_HOST: http://epochtalk
      SELENIUM_EPOCHTALK_PORT: 8080
    command: sh -c "./wait-for-it.sh epochtalk:8080 -t 120 && sleep 5 && npm run test-client"
  epochtalk:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
      - epoch
    links:
      - redis
      - postgres
    environment:
      PRIVATE_KEY: privateprivateprivatekeyprivateprivateprivatekey
      PGUSER: docker
      PGHOST: postgres
      PGPASSWORD: docker
      PGDATABASE: epochtalk
      PGPORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RECAPTCHA_SITE_KEY: ""
      RECAPTCHA_SECRET_KEY: ""
      WEBSOCKET_SERVER_PRIVATE_KEY: privateprivateprivatekeyprivateprivateprivatekey
      WEBSOCKET_SERVER_REDIS_HOST: redis
      WEBSOCKET_SERVER_REDIS_PORT: 6379
      HOST: 0.0.0.0
      PORT: 8080
      PUBLIC_URL: http://localhost:8080
      EMAILER_SENDER: e@ma.il
      EMAILER_OPTIONS_HOST: epochtalk-api-tests
      EMAILER_OPTIONS_PORT: 1025
      EMAILER_OPTIONS_IGNORE_TLS: "true"
      EMAILER_OPTIONS_SECURE: "false"
      RATE_LIMITING_GET_INTERVAL: -1
      RATE_LIMITING_PUT_INTERVAL: -1
      RATE_LIMITING_POST_INTERVAL: -1
      RATE_LIMITING_DELETE_INTERVAL: -1
  epoch:
    image: quay.io/epochtalk/epoch:1.0.0
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      MIX_ENV: prod
      DATABASE_USER: docker
      DATABASE_PASSWORD: docker
      DATABASE_NAME: epochtalk
      DATABASE_HOST: postgres
  redis:
    image: redis:4.0.1
    user: redis
  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
  chrome:
    image: selenium/standalone-chrome
